### ISSUE TITLE
Add Dependabot config to all my Python repositories

### ISSUE THREAD

**Issue by alexwlchan** [alexwlchan/alexwlchan#1]
I think it's enough to add the following config in `.github/dependabot.yml`:

```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
```
