### ISSUE TITLE
Add the `github-actions` ecosystem to all my Dependabot config

### ISSUE THREAD

**Issue by alexwlchan** [alexwlchan/alexwlchan#5]
This is something I spotted in the HTML-Proofer repo, see https://github.com/gjtorikian/html-proofer/blob/ee2c50e89adb977d56eb919d6dff107ee60490db/.github/dependabot.yml#L3-L9

```yml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
```

This seems like a useful thing I should add to all of my other repos!
