### ISSUE TITLE
Add a schedule to my Dependabot updates

### ISSUE THREAD

**Issue by alexwlchan** [alexwlchan/alexwlchan#8]

**Comment by alexwlchan** [comment]
Here's my suggested schedule: 9am UTC. This means all the updates will arrive once during the day, rather than trickling in.

```yml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
```

I'll add this to repos as Dependabot updates come in.
